spring:
  application:
    name: il_service
  mvc:
    static-path-pattern: /static/**
server:
  port: 8080
app:
  feign:
    customer:
      url: 127.0.0.1:8083
    product:
      url: 127.0.0.1:8081
    path:
      smartphones: /smartphone
      laptops: /laptop
      customers: /customer
  jwt:
    signing-key: sdafjkaksdfjasdfjfasdklfjfkasdfjasdkfjfkasdfjfdsajsdsdafasdfasdfsdaff32rfwf